#!/usr/bin/env python3

import os, sys, subprocess, configparser, shutil

def isbadipv4(s):
    pieces = s.split('.')
    if len(pieces) != 4: return True
    try: return not all(0<=int(p)<256 for p in pieces)
    except ValueError: return True

if __name__ == '__main__':
    if os.geteuid() == 0:
        print('Checking if installation files are present')
        allFilesPresent = True
        if not os.path.isfile('./mythrecmaze.py'):
            print('mythrecmaze.py could not be found')
            allFilesPresent = False
        if not os.path.isfile('./mythrecmaze.desktop'):
            print('mythrecmaze.desktop could not be found')
            allFilesPresent = False
        if not os.path.isfile('./mythrecmaze.svg'):
            print('mythrecmaze.svg could not be found')
            allFilesPresent = False
        if not allFilesPresent:
            print('No changes made')
            print('Exiting')
            sys.exit(0)
        has_homepath = os.getcwd()
        home_position = has_homepath.find('home/')
        if home_position < 0:
            print('Install script must be run from subdirectory in home directory')
            print('No changes made')
            print('Exiting')
            sys.exit(0)
        else:
            homepath = has_homepath[0:home_position+5]
            for i in range(len(has_homepath)-home_position-5):
                if has_homepath[i+home_position+5] == '/':
                    break
                else:
                    homepath = homepath + has_homepath[i+home_position+5]
        if os.path.isdir('/opt/mythrecmaze'):
            shutil.rmtree('/opt/mythrecmaze')
        os.mkdir('/opt/mythrecmaze')
        if os.path.isfile(homepath + '/.mythrecmaze/mythrecmaze.cfg'):
            os.rename(homepath + '/.mythrecmaze/mythrecmaze.cfg',homepath + '/.mythrecmaze/mythrecmazeOLD.cfg')
        config = configparser.RawConfigParser()
        config.add_section('userhomepath')
        config.set('userhomepath', 'uhp', homepath)
        with open('/opt/mythrecmaze/userhomepath.dat', 'w') as configfile:
            config.write(configfile)
        if 'mythtv' in homepath:
            mythlanip = input('Enter MythTV backend IP address (example: 192.168.1.50) --> ')
            if isbadipv4(mythlanip):
                print('Aborting (invalid MythTV backend server IP address)')
                sys.exit(0)
            mythport = input('Enter MythTV backend web server port (default: 6544) --> ')
            if len(mythport) == 0:
                mythport = '6544'
            elif not mythport.isdigit():
                print('Aborting (invalid MythTV backend web server port number)')
                sys.exit(0)
            mythsourceid = input('Enter MythTV channel source id (default: 1) --> ')
            if len(mythsourceid) == 0:
                mythsourceid = '1'
            elif not mythsourceid.isdigit():
                print('Aborting (invalid MythTV channel source id number)')
                sys.exit(0)
            mazetokens = [input('Enter single TVmaze API key --> ')]
            if len(mazetokens) == 0:
                print('Aborting (TVmaze API key is required)')
                sys.exit(0)
            while True:
                mazetoken = input('Enter another TVmaze API key or press enter if done --> ')
                if len(mazetoken) == 0:
                    break
                else:
                    mazetokens.append(mazetoken)
            config.add_section('mythrecmazesettings')
            config.set('mythrecmazesettings', 'mythlanip', mythlanip)
            config.set('mythrecmazesettings', 'mythport', mythport)
            config.set('mythrecmazesettings', 'mythsourceid', mythsourceid)
            config.set('mythrecmazesettings', 'mazetokens', ','.join(mazetokens))
            config.set('mythrecmazesettings', 'showdetails', 'False')
            showdetails = False
            with open(homepath + '/.mythrecmaze/mythrecmaze.cfg', 'w') as configfile:
                config.write(configfile)
        print('Installing mythrecmaze')
        shutil.move("./mythrecmaze.py", "/opt/mythrecmaze/mythrecmaze.py")
        shutil.move("./mythrecmaze.svg", "/opt/mythrecmaze/mythrecmaze.svg")
        shutil.move("./mythrecmaze.desktop", "/usr/share/applications/mythrecmaze.desktop")
        os.chmod("/opt/mythrecmaze", 0o755)
        os.chmod("/opt/mythrecmaze/mythrecmaze.py", 0o755)
        os.chmod("/usr/share/applications/mythrecmaze.desktop", 0o755)
        print('Mythrecmaze was successfully installed.')
        if not 'mythtv' in homepath:
             print('Start Mythrecmaze and change the settings.')
    else:
        print('This install script must be run with sudo')
        print('No changes made')
        print('Exiting')
